### create a meetup
POST http://localhost:8080/meetups
Content-Type: application/json
Authorization: milan

{
	"meetupId": "1",
	"topic": "axonMeetup"
}

### post a comment
POST http://localhost:8080/meetups/1/comments
Content-Type: text/plain
Authorization: petar

"awesome meetup"

### open comments in browser
http://localhost:8080/meetups/1/comments

### petar deletes a meetup
DELETE http://localhost:8080/meetups/1
Content-Type: application/json
Authorization: petar

### milan deletes a meetup
DELETE http://localhost:8080/meetups/1
Content-Type: application/json
Authorization: milan

###