version: "3.7"
services:
  meetup-command:
    hostname: meetup-command
    image: meetup-command
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
    ports:
      - '8080:8080'
  meetup-query:
    hostname: meetup-query
    image: meetup-query
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
      - SERVER_PORT=9090
    ports:
      - '9090:9090'
  axonserver:
    hostname: axonserver
    image: axoniq/axonserver:latest
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'