version: "3.7"

services:

  app:
    hostname: meetup
    image: meetup_app
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
    ports:
      - '8080:8080'
    depends_on:
      - axonserver

  axonserver:
    hostname: axonserver
    image: axoniq/axonserver:latest
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'