version: "3"

services:
  meetup:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - axonserver
    network_mode: "host"

  axonserver:
    image: axoniq/axonserver:latest
    ports:
      - 8024:8024
      - 8124:8124